apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: beehive
  description: |
    Beehive is a UI for managing DSPs kubernetes deployments in both BEE and live environments
  tags:
    - typescript
    - remix
    - beehive
    - kubernetes
    - dsp-devops
  annotations:
    github.com/project-slug: broadinstitute/beehive
spec:
  type: service
  lifecycle: production
  owner: dsp-devops
  dependsOn:
    - component:sherlock
  consumesApis:
    - sherlock-api
