name: check
on:
  pull_request:
    branches:
      - main
jobs:
  check:
    permissions:
      id-token: "write"
    uses: broadinstitute/sherlock/.github/workflows/client-get-environment.yaml@DDO-2520-more-actions
    with:
      environment-name: dev
  print:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: |
          echo ${{ needs.check.outputs.lifecycle }}
