name: "Test"
on:
  pull_request:
    branches:
      - main
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
      - run: npm ci
      - run: npm test
